HTML_CodeRewiev
yogik1909/fullStack pull request #1
Opened 2024-10-24 12:49 UTC by yogik1909

2024-10-24 19:25 UTC, Levitinn requested changes

2024-10-24 19:25 UTC, Levitinn commented on 1-blog/blog.html
> +                <li>Мой блог</li>
пункты меню должны быть ссылками

2024-10-24 19:25 UTC, Levitinn commented on 1-blog/blog.html
> +
лишние пустые строки

2024-10-24 19:25 UTC, Levitinn commented on 1-blog/blog.html
> +        <img src="img/Ellipse 1.svg" alt="Аватар автора">
каждый имг стоит оборачивать в отдельный див. это позволит гораздо проще управлять размерами изображения в будущем

2024-10-24 19:25 UTC, Levitinn commented on 1-blog/blog.html
> +        <div>
у картинки и у контента (фио, профессия) должен быть один общий див обертка так как это один смысловой элемент

2024-10-24 19:25 UTC, Levitinn commented on 1-blog/blog.html
> +            <img src="img/4f3f91ff718dae25d01f84692996a2cd.png" alt="Красивое изображения персонального компьютера"
див обертка тоже нужна

2024-10-24 19:25 UTC, Levitinn commented on 1-blog/blog.html
> +
лишняя пустая строка

2024-10-24 19:25 UTC, Levitinn commented on 1-blog/blog.html
> +
и здесь

2024-10-24 19:25 UTC, Levitinn commented on 2-form/regform.html
> +                <input type="text" name="Name" id="Name" placeholder="Имя">
каждый инпут, так же, стоит оборачивать в отдельный див\label по тем же причинам, что и с изображениями. а так же, многими стилями инпута нельзя управлять с помощью css, а вот задавать стили диву, в который обернут инпут - можно

2024-10-24 22:44 UTC, yogik1909 commented on 1-blog/blog.html
> +
VS Code сам добавляет пустую строку между закрывашкой тела и закрывашкой html, так же и между открывашками.

2024-10-27 21:38 UTC, Levitinn approved these changes

2024-10-28 06:08 UTC, merged