12.10 Block model code review
yogik1909/fullStack pull request #2
Opened 2024-11-06 13:56 UTC by yogik1909

2024-11-07 19:22 UTC, Levitinn requested changes

2024-11-07 19:22 UTC, Levitinn commented on 1-blog/blog.html
>              <img src="img/Ellipse 1.svg" alt="Аватар автора">
у каждого имг всегда долден быть свой див-обертка. так будет проще задавать размеры изображениям.

2024-11-07 19:22 UTC, Levitinn commented on 2-form/regform.html
по макету, у тебя есть блок с белым фоном, на фоне другого фона. это значит, тебе нужно сделать доп обертку для всей формы, чтобы задавать ей стили. все остальное  хорошо

2024-11-11 22:36 UTC, yogik1909 commented on 1-blog/blog.html
> +            <p id="persone">Наталья Васильева</p>
Мои убеждения:
- Кажется, что в принципе использование класса подразумевает **переиспользование** этого класса в структуре кода или разметки. Идентификатор же необходим, как и было сказано в лекциях, дается экземплярам уникальным и не повторяющимся. 
Фактически на этой странице появляется много классов, а переиспользуются всего пара из них (грубо говоря тут классы ≈ идентификаторам). Поэтому в рамках этой практики, наверное, не очень очевидны преимущества этих подходов. 
Наверное, более заметно их различие было бы в странице с множественным повторением одних и тех же элементов кратно, например, верстка интернет-магазина с отображением карточек товаров.

2025-01-09 19:27 UTC, Levitinn commented on 1-blog/blog.html
> +            <p id="persone">Наталья Васильева</p>
ты прав на счет того, что ид всегда должны быть уникальны. но будет проще понять если принять тот факт, что по большей части, ИД используются для обращения к элементам через ЖС. для всего остального подойдут классы. даже если такой класс будет лишь один на странице - это нормально.

2025-01-09 19:28 UTC, Levitinn approved these changes

2025-01-09 21:15 UTC, merged